//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onyx.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CustomerSetting
    {
        [Key]
        public int CustomerSettingID { get; set; }
        public int KeyID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
